# Site settings
title: "Susana Quartin's resume"
#description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Susana Quartin"
resume_title:                   "Data Scientist"
resume_contact_email:
  "susanaquartin@gmail.com"
resume_header_contact_info: '(+351) 926 302 901 | <span class="spamspan">
<span class="u">susanaquartin</span>
[at]
<span class="d">gmail [dot] com</span>
</span>'
resume_header_intro: "<p>Mathematics background with a gaining interest in programming. I enjoy the challenges of modelling a business problem in mathematical terms, taking care of data ingestion, munging and cleaning for a specific task, coming up with the best mongo query, debugging some nasty code, setting up an A/B test, or getting my hands dirty on some new tool.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_skills:          true
resume_section_projects:        true
resume_section_education:       true
#resume_section_recognition:     true
#resume_section_links:           false
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/quartin"
  resume_linkedin_url:          "https://www.linkedin.com/in/susana-quartin-8443b549"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
